$(document).ready(function() {

    $(".page-section").hide(); 
    $("#section-archive").show(); 
    $("#archive-default").show(); 
    $("#archive-detail").hide();

    const archiveData = {
        "16mm": {
            summary: "Introduced by Eastman Kodak in 1923, the 16mm film was a portable and cost-effective alternative to the 35mm industry standard. Originally intended for amateur filmmakers and television production, its accessibility allowed independent directors and producers to bypass the financial and technical constraints of the major studio systems, effectively democratizing the cinematic medium. The defining aesthetic of 16mm is its film grain. Due to the smaller physical frame size compared to 35mm, the silver halide crystals—the organic building blocks of the image—become more visible upon enlargement. While once considered a technical limitation, this texture is now recognized as a source of physical depth that digital sensors cannot replicate.",
            movies: [
                { title: "NIGHT OF THE LIVING DEAD", director: "George A. Romero", type: "Black & white", year: 1968, frames: ["living-images/living1.png", "living-images/living2.png", "living-images/living3.png", "living-images/living4.png", "living-images/living5.png", "living-images/living6.png", "living-images/living7.png", "living-images/living8.png", "living-images/living9.png", "living-images/living10.png", "living-images/living11.png", "living-images/living12.png", "living-images/living13.png", "living-images/living14.png", "living-images/living15.png", "living-images/living16.png", "living-images/living17.png", "living-images/living18.png", "living-images/living19.png", "living-images/living20.png"] },
                { title: "THE TEXAS CHAINSAW MASSACRE", director: "Tobe Hooper", type: "Color", year: 1974, frames: ["texas-images/texas1.png", "texas-images/texas2.png", "texas-images/texas3.png", "texas-images/texas4.png", "texas-images/texas5.png", "texas-images/texas6.png", "texas-images/texas7.png", "texas-images/texas8.png", "texas-images/texas9.png", "texas-images/texas10.png", "texas-images/texas11.png", "texas-images/texas12.png", "texas-images/texas13.png", "texas-images/texas14.png", "texas-images/texas15.png", "texas-images/texas16.png", "texas-images/texas17.png", "texas-images/texas18.png", "texas-images/texas19.png", "texas-images/texas20.png", "texas-images/texas21.png", "texas-images/texas22.png"] },
                { title: "THE EVIL DEAD", director: "Sam Raimi", type: "Color", year: 1981, frames: ["evildead-images/evildead1.png", "evildead-images/evildead2.png", "evildead-images/evildead3.png", "evildead-images/evildead4.png", "evildead-images/evildead5.png", "evildead-images/evildead6.png", "evildead-images/evildead7.png", "evildead-images/evildead8.png", "evildead-images/evildead9.png", "evildead-images/evildead10.png", "evildead-images/evildead11.png", "evildead-images/evildead12.png", "evildead-images/evildead13.png", "evildead-images/evildead14.png", "evildead-images/evildead15.png", "evildead-images/evildead16.png", "evildead-images/evildead17.png", "evildead-images/evildead18.png", "evildead-images/evildead19.png", "evildead-images/evildead20.png", "evildead-images/evildead21.png", "evildead-images/evildead22.png"] },
                { title: "THIS IS SPINAL TAP", director: "Rob Reiner", type: "Color", year: 1984, frames: ["spinal-images/spinal1.png", "spinal-images/spinal2.png", "spinal-images/spinal3.png", "spinal-images/spinal4.png", "spinal-images/spinal5.png", "spinal-images/spinal6.png", "spinal-images/spinal7.png", "spinal-images/spinal8.png", "spinal-images/spinal9.png", "spinal-images/spinal10.png", "spinal-images/spinal11.png", "spinal-images/spinal12.png", "spinal-images/spinal13.png", "spinal-images/spinal14.png", "spinal-images/spinal15.png", "spinal-images/spinal16.png", "spinal-images/spinal17.png", "spinal-images/spinal18.png", "spinal-images/spinal19.png", "spinal-images/spinal20.png", "spinal-images/spinal21.png", "spinal-images/spinal22.png"]},
                { title: "SLACKER", director: "Richard Linklater", type: "color", year: 1990, frames: ["slacker-images/slacker1.png", "slacker-images/slacker2.png", "slacker-images/slacker3.png", "slacker-images/slacker4.png", "slacker-images/slacker5.png", "slacker-images/slacker6.png", "slacker-images/slacker7.png", "slacker-images/slacker8.png", "slacker-images/slacker9.png", "slacker-images/slacker10.png", "slacker-images/slacker11.png", "slacker-images/slacker12.png", "slacker-images/slacker13.png", "slacker-images/slacker14.png", "slacker-images/slacker15.png", "slacker-images/slacker16.png", "slacker-images/slacker17.png", "slacker-images/slacker18.png", "slacker-images/slacker19.png", "slacker-images/slacker20.png"] },
                { title: "LEAVING LAS VEGAS", director: "Mike Figgis", type: "Color", year: 1995, frames: ["leaving-images/leaving1.png", "leaving-images/leaving2.png", "leaving-images/leaving3.png", "leaving-images/leaving4.png", "leaving-images/leaving5.png", "leaving-images/leaving6.png", "leaving-images/leaving7.png", "leaving-images/leaving8.png", "leaving-images/leaving9.png", "leaving-images/leaving10.png", "leaving-images/leaving11.png", "leaving-images/leaving12.png", "leaving-images/leaving13.png", "leaving-images/leaving14.png", "leaving-images/leaving15.png", "leaving-images/leaving16.png", "leaving-images/leaving17.png", "leaving-images/leaving18.png"] },
                { title: "PI", director: "Darren Aronofsky", type: "Black & white", year: 1998, frames:["pi-images/pi1.png", "pi-images/pi2.png", "pi-images/pi3.png", "pi-images/pi4.png", "pi-images/pi5.png", "pi-images/pi6.png", "pi-images/pi7.png", "pi-images/pi8.png", "pi-images/pi9.png", "pi-images/pi10.png", "pi-images/pi11.png", "pi-images/pi12.png", "pi-images/pi13.png", "pi-images/pi14.png", "pi-images/pi15.png", "pi-images/pi16.png", "pi-images/pi17.png", "pi-images/pi18.png", "pi-images/pi19.png", "pi-images/pi20.png"] },
                { title: "THE BLAIR WITCH PROJECT", director: "Daniel Myrick & Eduardo Sánchez", type: "Color / Black & white", year: 1999, frames: ["blair-images/blair1.png", "blair-images/blair2.png", "blair-images/blair3.png", "blair-images/blair4.png", "blair-images/blair5.png", "blair-images/blair6.png", "blair-images/blair7.png", "blair-images/blair8.png", "blair-images/blair9.png", "blair-images/blair10.png", "blair-images/blair11.png", "blair-images/blair12.png", "blair-images/blair13.png", "blair-images/blair14.png", "blair-images/blair15.png", "blair-images/blair16.png", "blair-images/blair17.png", "blair-images/blair18.png" ] },
                { title: "CITY OF GOD", director: "Fernando Meirelles & Kátia Lund", type: "Color", year: 2002, frames:["city-of-images/city-of1.png", "city-of-images/city-of2.png", "city-of-images/city-of3.png", "city-of-images/city-of4.png", "city-of-images/city-of5.png", "city-of-images/city-of6.png", "city-of-images/city-of7.png", "city-of-images/city-of8.png", "city-of-images/city-of9.png", "city-of-images/city-of10.png", "city-of-images/city-of11.png", "city-of-images/city-of12.png", "city-of-images/city-of13.png", "city-of-images/city-of14.png", "city-of-images/city-of15.png", "city-of-images/city-of16.png", "city-of-images/city-of17.png", "city-of-images/city-of18.png", "city-of-images/city-of19.png", "city-of-images/city-of20.png"]},
                { title: "THE SQUID AND THE WHALE", director: "Noah Baumbach", type: "Color", year: 2005, frames: ["squid-images/squid1.png", "squid-images/squid2.png", "squid-images/squid3.png", "squid-images/squid4.png", "squid-images/squid5.png", "squid-images/squid6.png", "squid-images/squid7.png", "squid-images/squid8.png", "squid-images/squid9.png", "squid-images/squid10.png", "squid-images/squid11.png", "squid-images/squid12.png", "squid-images/squid13.png", "squid-images/squid14.png", "squid-images/squid15.png", "squid-images/squid16.png", "squid-images/squid17.png", "squid-images/squid18.png", "squid-images/squid19.png", "squid-images/squid20.png"] },
                { title: "MOONRISE KINGDOM", director: "Wes Anderson", type: "Color", year: 2012, frames: ["moonrise-images/moonrise1.png", "moonrise-images/moonrise2.png", "moonrise-images/moonrise3.png", "moonrise-images/moonrise4.png", "moonrise-images/moonrise5.png", "moonrise-images/moonrise6.png", "moonrise-images/moonrise7.png", "moonrise-images/moonrise8.png", "moonrise-images/moonrise9.png", "moonrise-images/moonrise10.png", "moonrise-images/moonrise11.png", "moonrise-images/moonrise12.png", "moonrise-images/moonrise13.png", "moonrise-images/moonrise14.png", "moonrise-images/moonrise15.png", "moonrise-images/moonrise16.png", "moonrise-images/moonrise17.png", "moonrise-images/moonrise18.png", "moonrise-images/moonrise19.png", "moonrise-images/moonrise20.png", "moonrise-images/moonrise21.png", "moonrise-images/moonrise22.png"]},
                { title: "MOTHER!", director: "Darren Aronofsky", type: "Color", year: 2017, frames: ["mother-images/mother1.png", "mother-images/mother2.png", "mother-images/mother3.png", "mother-images/mother4.png", "mother-images/mother5.png", "mother-images/mother6.png", "mother-images/mother7.png", "mother-images/mother8.png", "mother-images/mother9.png", "mother-images/mother10.png", "mother-images/mother11.png", "mother-images/mother12.png", "mother-images/mother13.png", "mother-images/mother14.png", "mother-images/mother15.png", "mother-images/mother16.png", "mother-images/mother17.png", "mother-images/mother18.png", "mother-images/mother19.png", "mother-images/mother20.png", "mother-images/mother21.png", "mother-images/mother22.png"] },
                { title: "MID90S", director: "Jonah Hill", type: "Color", year: 2018, frames: ["mid-images/mid1.png", "mid-images/mid2.png", "mid-images/mid3.png", "mid-images/mid4.png", "mid-images/mid5.png", "mid-images/mid6.png", "mid-images/mid7.png", "mid-images/mid8.png", "mid-images/mid9.png", "mid-images/mid10.png", "mid-images/mid11.png", "mid-images/mid12.png", "mid-images/mid13.png", "mid-images/mid14.png", "mid-images/mid15.png", "mid-images/mid16.png", "mid-images/mid17.png", "mid-images/mid18.png", "mid-images/mid19.png", "mid-images/mid20.png"] },
                { title: "THE SMASHING MACHINE", director: "Benny Safdie", type: "Color", year: 2025, frames: ["smashing-images/smashing1.png", "smashing-images/smashing2.png", "smashing-images/smashing3.png", "smashing-images/smashing4.png", "smashing-images/smashing5.png", "smashing-images/smashing6.png", "smashing-images/smashing7.png", "smashing-images/smashing8.png", "smashing-images/smashing9.png", "smashing-images/smashing10.png", "smashing-images/smashing11.png", "smashing-images/smashing12.png", "smashing-images/smashing13.png", "smashing-images/smashing14.png", "smashing-images/smashing15.png", "smashing-images/smashing16.png", "smashing-images/smashing17.png", "smashing-images/smashing18.png", "smashing-images/smashing19.png", "smashing-images/smashing20.png", "smashing-images/smashing21.png", "smashing-images/smashing22.png"] }
            ]
        },
        "35mm": {
            summary: "Since its standardization by the Motion Picture Patents Company in 1909, 35mm has remained as the backbone of global cinema. Its four-perforation frame structure offered a balance between chemical resolution and mechanical reliability, establishing a globally used visual format that defined the 20th century. This format provides a clarity wich a natural sharpness of the scenes. The 1.37:1 Academy ratio or the 2.39:1 Anamorphic stretch on 35mm defined the golden ratio of cinema over 100 years.",
            movies: [
                { title: "METROPOLIS", director: "Fritz Lang",type: "Black & white", year: 1927, frames: ["metro-images/metro1.png", "metro-images/metro2.png", "metro-images/metro3.png", "metro-images/metro4.png", "metro-images/metro5.png", "metro-images/metro6.png", "metro-images/metro7.png", "metro-images/metro8.png", "metro-images/metro9.png", "metro-images/metro10.png", "metro-images/metro11.png", "metro-images/metro12.png", "metro-images/metro13.png", "metro-images/metro14.png", "metro-images/metro15.png", "metro-images/metro16.png", "metro-images/metro17.png", "metro-images/metro18.png", "metro-images/metro19.png", "metro-images/metro20.png"] },
                { title: "WIZARD OF OZ", director: "Victor Fleming", type: "Color", year: 1939, frames: ["oz-images/oz1.png", "oz-images/oz2.png", "oz-images/oz3.png", "oz-images/oz4.png", "oz-images/oz5.png", "oz-images/oz6.png", "oz-images/oz7.png", "oz-images/oz8.png", "oz-images/oz9.png", "oz-images/oz10.png", "oz-images/oz11.png", "oz-images/oz12.png", "oz-images/oz13.png", "oz-images/oz14.png", "oz-images/oz15.png", "oz-images/oz16.png", "oz-images/oz17.png", "oz-images/oz18.png", "oz-images/oz19.png", "oz-images/oz20.png"] },
                { title: "CITIZEN KANE", director: "Orson Welles", type: "Black & white", year: 1941, frames: ["kane-images/kane1.png", "kane-images/kane2.png", "kane-images/kane3.png", "kane-images/kane4.png", "kane-images/kane5.png", "kane-images/kane6.png", "kane-images/kane7.png", "kane-images/kane8.png", "kane-images/kane9.png", "kane-images/kane10.png", "kane-images/kane11.png", "kane-images/kane12.png", "kane-images/kane13.png", "kane-images/kane14.png", "kane-images/kane15.png", "kane-images/kane16.png", "kane-images/kane17.png", "kane-images/kane18.png"] },
                { title: "STAGE FRIGHT", director: "Alfred Hitchcock", type: "Black & white", year: 1950, frames: ["stagefright-images/stagefright1.png", "stagefright-images/stagefright2.png", "stagefright-images/stagefright3.png", "stagefright-images/stagefright4.png", "stagefright-images/stagefright5.png", "stagefright-images/stagefright6.png", "stagefright-images/stagefright7.png", "stagefright-images/stagefright8.png", "stagefright-images/stagefright9.png", "stagefright-images/stagefright10.png", "stagefright-images/stagefright11.png", "stagefright-images/stagefright12.png", "stagefright-images/stagefright13.png", "stagefright-images/stagefright14.png", "stagefright-images/stagefright15.png", "stagefright-images/stagefright16.png", "stagefright-images/stagefright17.png", "stagefright-images/stagefright18.png"] },
                { title: "RIO BRAVO", director: "Howard Hawks", type: "Color", year: 1959, frames: ["bravo-images/bravo1.png", "bravo-images/bravo2.png", "bravo-images/bravo3.png", "bravo-images/bravo4.png", "bravo-images/bravo5.png", "bravo-images/bravo6.png", "bravo-images/bravo7.png", "bravo-images/bravo8.png", "bravo-images/bravo9.png", "bravo-images/bravo10.png", "bravo-images/bravo11.png", "bravo-images/bravo12.png", "bravo-images/bravo13.png", "bravo-images/bravo14.png", "bravo-images/bravo15.png", "bravo-images/bravo16.png", "bravo-images/bravo17.png", "bravo-images/bravo18.png", "bravo-images/bravo19.png", "bravo-images/bravo20.png"]},
                { title: "FROM RUSSIA WITH LOVE", director: "Terence Young", type: "Color", year: 1963, frames: ["russia-images/russia1.png", "russia-images/russia2.png", "russia-images/russia3.png", "russia-images/russia4.png", "russia-images/russia5.png", "russia-images/russia6.png", "russia-images/russia7.png", "russia-images/russia8.png", "russia-images/russia9.png", "russia-images/russia10.png", "russia-images/russia11.png", "russia-images/russia12.png", "russia-images/russia13.png", "russia-images/russia14.png", "russia-images/russia15.png", "russia-images/russia16.png", "russia-images/russia17.png", "russia-images/russia18.png", "russia-images/russia19.png", "russia-images/russia20.png"] },
                { title: "A HARD DAY'S NIGHT", director: "Richard Lester", type: "Black & white", year: 1964, frames: ["hard-images/hard1.png", "hard-images/hard2.png", "hard-images/hard3.png", "hard-images/hard4.png", "hard-images/hard5.png", "hard-images/hard6.png", "hard-images/hard7.png", "hard-images/hard8.png", "hard-images/hard9.png", "hard-images/hard10.png", "hard-images/hard11.png", "hard-images/hard12.png", "hard-images/hard13.png", "hard-images/hard14.png", "hard-images/hard15.png", "hard-images/hard16.png", "hard-images/hard17.png", "hard-images/hard18.png", "hard-images/hard19.png", "hard-images/hard20.png"]},
                { title: "BULLITT", director: "Peter Yates", type: "Color", year: 1968, frames:["bullitt-images/bullitt1.png", "bullitt-images/bullitt2.png", "bullitt-images/bullitt3.png", "bullitt-images/bullitt4.png", "bullitt-images/bullitt5.png", "bullitt-images/bullitt6.png", "bullitt-images/bullitt7.png", "bullitt-images/bullitt8.png", "bullitt-images/bullitt9.png", "bullitt-images/bullitt10.png", "bullitt-images/bullitt11.png", "bullitt-images/bullitt12.png", "bullitt-images/bullitt13.png", "bullitt-images/bullitt14.png", "bullitt-images/bullitt15.png", "bullitt-images/bullitt16.png", "bullitt-images/bullitt17.png", "bullitt-images/bullitt18.png", "bullitt-images/bullitt19.png", "bullitt-images/bullitt20.png"]},
                { title: "A CLOCKWORK ORANGE", director: "Stanley Kubrick", type: "color", year: 1971, frames:["orange-images/orange1.png", "orange-images/orange2.png", "orange-images/orange3.png", "orange-images/orange4.png", "orange-images/orange5.png", "orange-images/orange6.png", "orange-images/orange7.png", "orange-images/orange8.png", "orange-images/orange9.png", "orange-images/orange10.png", "orange-images/orange11.png", "orange-images/orange12.png", "orange-images/orange13.png", "orange-images/orange14.png", "orange-images/orange15.png", "orange-images/orange16.png", "orange-images/orange17.png", "orange-images/orange18.png", "orange-images/orange19.png", "orange-images/orange20.png"]},
                { title: "PHANTOM OF THE PARADISE", director: "Brian De Palma", type: "Color", year: 1974, frames: ["phantom-images/phantom1.png", "phantom-images/phantom2.png", "phantom-images/phantom3.png", "phantom-images/phantom4.png", "phantom-images/phantom5.png", "phantom-images/phantom6.png", "phantom-images/phantom7.png", "phantom-images/phantom8.png", "phantom-images/phantom9.png", "phantom-images/phantom10.png", "phantom-images/phantom11.png", "phantom-images/phantom12.png", "phantom-images/phantom13.png", "phantom-images/phantom14.png", "phantom-images/phantom15.png", "phantom-images/phantom16.png", "phantom-images/phantom17.png", "phantom-images/phantom18.png", "phantom-images/phantom19.png", "phantom-images/phantom20.png"] },
                { title: "SUSPIRIA", director: "Dario Argento", type: "Color", year: 1977, frames: ["suspiria-images/suspiria1.png", "suspiria-images/suspiria2.png", "suspiria-images/suspiria3.png", "suspiria-images/suspiria4.png", "suspiria-images/suspiria5.png", "suspiria-images/suspiria6.png", "suspiria-images/suspiria7.png", "suspiria-images/suspiria8.png", "suspiria-images/suspiria9.png", "suspiria-images/suspiria10.png", "suspiria-images/suspiria11.png", "suspiria-images/suspiria12.png", "suspiria-images/suspiria13.png", "suspiria-images/suspiria14.png", "suspiria-images/suspiria15.png", "suspiria-images/suspiria16.png", "suspiria-images/suspiria17.png", "suspiria-images/suspiria18.png", "suspiria-images/suspiria19.png", "suspiria-images/suspiria20.png"]},
                { title: "SUPERMAN", director: "Richard Donner", type: "Color", year: 1978, frames:["superman-images/superman1.png", "superman-images/superman2.png", "superman-images/superman3.png", "superman-images/superman4.png", "superman-images/superman5.png", "superman-images/superman6.png", "superman-images/superman7.png", "superman-images/superman8.png", "superman-images/superman9.png", "superman-images/superman10.png", "superman-images/superman11.png", "superman-images/superman12.png", "superman-images/superman13.png", "superman-images/superman14.png", "superman-images/superman15.png", "superman-images/superman16.png", "superman-images/superman17.png", "superman-images/superman18.png", "superman-images/superman19.png", "superman-images/superman20.png" ] },
                { title: "ALTERED STATES", director: "Ken Russell", type: "Color", year: 1980, frames: ["altered-images/altered1.png", "altered-images/altered2.png", "altered-images/altered3.png", "altered-images/altered4.png", "altered-images/altered5.png", "altered-images/altered6.png", "altered-images/altered7.png", "altered-images/altered8.png", "altered-images/altered9.png", "altered-images/altered10.png", "altered-images/altered11.png", "altered-images/altered12.png", "altered-images/altered13.png", "altered-images/altered14.png", "altered-images/altered15.png", "altered-images/altered16.png", "altered-images/altered17.png", "altered-images/altered18.png", "altered-images/altered19.png", "altered-images/altered20.png"]},
                { title: "RAIDERS OF THE LOST ARK", director: "Steven Spielberg", type: "Color", year: 1981, frames: ["raiders-images/raiders1.png", "raiders-images/raiders2.png", "raiders-images/raiders3.png", "raiders-images/raiders4.png", "raiders-images/raiders5.png", "raiders-images/raiders6.png", "raiders-images/raiders7.png", "raiders-images/raiders8.png", "raiders-images/raiders9.png", "raiders-images/raiders10.png", "raiders-images/raiders11.png", "raiders-images/raiders12.png", "raiders-images/raiders13.png", "raiders-images/raiders14.png", "raiders-images/raiders15.png", "raiders-images/raiders16.png", "raiders-images/raiders17.png", "raiders-images/raiders18.png", "raiders-images/raiders19.png", "raiders-images/raiders20.png"] },
                { title: "1984", director: "Michael Anderson", type: "Color", year: 1984, frames:["1984-images/19841.png", "1984-images/19842.png", "1984-images/19843.png", "1984-images/19844.png", "1984-images/19845.png", "1984-images/19846.png", "1984-images/19847.png", "1984-images/19848.png", "1984-images/19849.png", "1984-images/198410.png", "1984-images/198411.png", "1984-images/198411-1.png", "1984-images/198412.png", "1984-images/198413.png", "1984-images/198414.png", "1984-images/198415.png", "1984-images/198416.png", "1984-images/198417.png", "1984-images/198418.png", "1984-images/198419.png"] },
                { title: "PEE-WEE'S BIG ADVENTURE", director: "Tim Burton", type: "Color", year: 1988, frames: ["peewee-images/peewee1.png", "peewee-images/peewee2.png", "peewee-images/peewee3.png", "peewee-images/peewee4.png", "peewee-images/peewee5.png", "peewee-images/peewee6.png", "peewee-images/peewee7.png", "peewee-images/peewee8.png", "peewee-images/peewee9.png", "peewee-images/peewee10.png", "peewee-images/peewee11.png", "peewee-images/peewee12.png", "peewee-images/peewee13.png", "peewee-images/peewee14.png", "peewee-images/peewee15.png", "peewee-images/peewee16.png", "peewee-images/peewee17.png", "peewee-images/peewee18.png" ] },
                { title: "HEATHERS", director: "Michael Lehmann", type: "Color", year: 1989, frames: ["heathers-images/heathers1.png", "heathers-images/heathers2.png", "heathers-images/heathers3.png", "heathers-images/heathers4.png", "heathers-images/heathers5.png", "heathers-images/heathers6.png", "heathers-images/heathers7.png", "heathers-images/heathers8.png", "heathers-images/heathers9.png", "heathers-images/heathers10.png", "heathers-images/heathers11.png", "heathers-images/heathers12.png", "heathers-images/heathers13.png", "heathers-images/heathers14.png", "heathers-images/heathers15.png", "heathers-images/heathers16.png", "heathers-images/heathers17.png", "heathers-images/heathers18.png"]},
                { title: "GOODFELLAS", director: "Martin Scorsese", type: "Color", year: 1990, frames:["goodfellas-images/goodfellas1.png", "goodfellas-images/goodfellas2.png", "goodfellas-images/goodfellas3.png", "goodfellas-images/goodfellas4.png", "goodfellas-images/goodfellas5.png", "goodfellas-images/goodfellas6.png", "goodfellas-images/goodfellas7.png", "goodfellas-images/goodfellas8.png", "goodfellas-images/goodfellas9.png", "goodfellas-images/goodfellas10.png", "goodfellas-images/goodfellas11.png", "goodfellas-images/goodfellas12.png", "goodfellas-images/goodfellas13.png", "goodfellas-images/goodfellas14.png", "goodfellas-images/goodfellas15.png", "goodfellas-images/goodfellas16.png", "goodfellas-images/goodfellas17.png", "goodfellas-images/goodfellas18.png", "goodfellas-images/goodfellas19.png", "goodfellas-images/goodfellas20.png"]},
                { title: "TERMINATOR 2: JUDGEMENT DAY", director: "James Cameron", type: "Color", year: 1991, frames:["terminator-images/terminator1.png", "terminator-images/terminator2.png", "terminator-images/terminator3.png", "terminator-images/terminator4.png", "terminator-images/terminator5.png", "terminator-images/terminator6.png", "terminator-images/terminator7.png", "terminator-images/terminator8.png", "terminator-images/terminator9.png", "terminator-images/terminator10.png", "terminator-images/terminator11.png", "terminator-images/terminator12.png", "terminator-images/terminator13.png", "terminator-images/terminator14.png", "terminator-images/terminator15.png", "terminator-images/terminator16.png", "terminator-images/terminator17.png", "terminator-images/terminator18.png", "terminator-images/terminator19.png", "terminator-images/terminator20.png"]},
                { title: "TWIN PEAKS: FIRE WALK WITH ME", director: "David Lynch", type: "Color", year: 1992, frames:["twin-images/twin1.png", "twin-images/twin2.png", "twin-images/twin3.png", "twin-images/twin4.png", "twin-images/twin5.png", "twin-images/twin6.png", "twin-images/twin7.png", "twin-images/twin8.png", "twin-images/twin9.png", "twin-images/twin10.png", "twin-images/twin11.png", "twin-images/twin12.png", "twin-images/twin13.png", "twin-images/twin14.png", "twin-images/twin15.png", "twin-images/twin16.png", "twin-images/twin17.png", "twin-images/twin18.png", "twin-images/twin19.png", "twin-images/twin20.png" ] },
                { title: "TRUE ROMANCE", director: "Tony Scott", type: "Color", year: 1993, frames:["true-images/true1.png", "true-images/true2.png", "true-images/true3.png", "true-images/true4.png", "true-images/true5.png", "true-images/true6.png", "true-images/true7.png", "true-images/true8.png", "true-images/true9.png", "true-images/true10.png", "true-images/true11.png", "true-images/true12.png", "true-images/true13.png", "true-images/true14.png", "true-images/true15.png", "true-images/true16.png", "true-images/true17.png", "true-images/true18.png", "true-images/true19.png", "true-images/true20.png"]},
                { title: "ED WOOD", director: "Tim Burton", type: "Black & white", year: 1994, frames:["ed-images/ed1.png", "ed-images/ed2.png", "ed-images/ed3.png", "ed-images/ed4.png", "ed-images/ed5.png", "ed-images/ed6.png", "ed-images/ed7.png", "ed-images/ed8.png", "ed-images/ed9.png", "ed-images/ed10.png", "ed-images/ed11.png", "ed-images/ed12.png", "ed-images/ed13.png", "ed-images/ed14.png", "ed-images/ed15.png", "ed-images/ed16.png", "ed-images/ed17.png", "ed-images/ed18.png", "ed-images/ed19.png", "ed-images/ed20.png"]},
                { title: "TO DIE FOR", director: "Gus Van Sant", type: "Color", year: 1995, frames:["die-images/die1.png", "die-images/die2.png", "die-images/die3.png", "die-images/die4.png", "die-images/die5.png", "die-images/die6.png", "die-images/die7.png", "die-images/die8.png", "die-images/die9.png", "die-images/die10.png", "die-images/die11.png", "die-images/die12.png", "die-images/die13.png", "die-images/die14.png", "die-images/die15.png", "die-images/die16.png", "die-images/die17.png", "die-images/die18.png", "die-images/die19.png", "die-images/die20.png"] },
                { title: "ROMEO + JULIET", director: "Baz Luhrmann", type: "Color", year: 1996, frames:["romeo-images/romeo2.png", "romeo-images/romeo3.png", "romeo-images/romeo4.png", "romeo-images/romeo5.png", "romeo-images/romeo6.png", "romeo-images/romeo7.png", "romeo-images/romeo8.png", "romeo-images/romeo9.png", "romeo-images/romeo10.png", "romeo-images/romeo11.png", "romeo-images/romeo12.png", "romeo-images/romeo13.png", "romeo-images/romeo14.png", "romeo-images/romeo15.png", "romeo-images/romeo16.png", "romeo-images/romeo17.png", "romeo-images/romeo18.png", "romeo-images/romeo19.png", "romeo-images/romeo20.png"] },
                { title: "HANA-BI", director: "Takeshi Kitano", type: "Color", year: 1997, frames:["hanabi-images/hanabi1.png", "hanabi-images/hanabi2.png", "hanabi-images/hanabi3.png", "hanabi-images/hanabi4.png", "hanabi-images/hanabi5.png", "hanabi-images/hanabi6.png", "hanabi-images/hanabi7.png", "hanabi-images/hanabi8.png", "hanabi-images/hanabi9.png", "hanabi-images/hanabi10.png", "hanabi-images/hanabi11.png", "hanabi-images/hanabi12.png", "hanabi-images/hanabi13.png", "hanabi-images/hanabi14.png", "hanabi-images/hanabi15.png", "hanabi-images/hanabi16.png"] },
                { title: "FEAR AND LOATHING IN LAS VEGAS", director: "Terry Gilliam", type: "Color", year: 1998, frames:["fear-images/fear1.png", "fear-images/fear2.png", "fear-images/fear3.png", "fear-images/fear4.png", "fear-images/fear5.png", "fear-images/fear6.png", "fear-images/fear7.png", "fear-images/fear8.png", "fear-images/fear9.png", "fear-images/fear10.png", "fear-images/fear11.png", "fear-images/fear12.png", "fear-images/fear13.png", "fear-images/fear14.png", "fear-images/fear15.png", "fear-images/fear16.png", "fear-images/fear17.png", "fear-images/fear18.png"] },
                { title: "THE MATRIX", director: "The Wachowskis", type: "Color", year: 1999, frames: ["matrix-images/matrix1.png", "matrix-images/matrix2.png", "matrix-images/matrix3.png", "matrix-images/matrix4.png", "matrix-images/matrix5.png", "matrix-images/matrix6.png", "matrix-images/matrix7.png", "matrix-images/matrix8.png", "matrix-images/matrix9.png", "matrix-images/matrix10.png", "matrix-images/matrix11.png", "matrix-images/matrix12.png", "matrix-images/matrix13.png", "matrix-images/matrix14.png", "matrix-images/matrix15.png", "matrix-images/matrix16.png", "matrix-images/matrix17.png", "matrix-images/matrix18.png", "matrix-images/matrix19.png", "matrix-images/matrix20.png"] },
                { title: "BATTLE ROYALE", director: "Kinji Fukasaku", type: "Color", year: 2000, frames:["battle-images/battle1.png", "battle-images/battle2.png", "battle-images/battle3.png", "battle-images/battle4.png", "battle-images/battle5.png", "battle-images/battle6.png", "battle-images/battle7.png", "battle-images/battle8.png", "battle-images/battle9.png", "battle-images/battle10.png", "battle-images/battle11.png", "battle-images/battle12.png", "battle-images/battle13.png", "battle-images/battle14.png", "battle-images/battle15.png", "battle-images/battle16.png", "battle-images/battle17.png", "battle-images/battle18.png", "battle-images/battle19.png", "battle-images/battle20.png"]},
                { title: "THE OTHERS", director: "Alejandro Amenábar", type: "Color", year: 2001, frames:["others-images/others1.png", "others-images/others2.png", "others-images/others3.png", "others-images/others4.png", "others-images/others5.png", "others-images/others6.png", "others-images/others7.png", "others-images/others8.png", "others-images/others9.png", "others-images/others10.png", "others-images/others11.png", "others-images/others12.png", "others-images/others13.png", "others-images/others14.png", "others-images/others15.png", "others-images/others16.png", "others-images/others17.png", "others-images/others18.png", "others-images/others19.png", "others-images/others20.png"] },
                { title: "CATCH ME IF YOU CAN", director: "Steven Spielberg", type: "Color", year: 2002, frames:["catch-images/catch1.png", "catch-images/catch2.png", "catch-images/catch3.png", "catch-images/catch4.png", "catch-images/catch5.png", "catch-images/catch6.png", "catch-images/catch7.png", "catch-images/catch8.png", "catch-images/catch9.png", "catch-images/catch10.png", "catch-images/catch11.png", "catch-images/catch12.png", "catch-images/catch13.png", "catch-images/catch14.png", "catch-images/catch15.png", "catch-images/catch16.png", "catch-images/catch17.png", "catch-images/catch18.png" ] },
                { title: "OLDBOY", director: "Park Chan-Wook", type: "Color", year: 2003, frames: ["/old-images/old1.png", "/old-images/old2.png", "/old-images/old3.png", "/old-images/old4.png", "/old-images/old5.png", "/old-images/old6.png", "/old-images/old7.png", "/old-images/old8.png", "/old-images/old9.png", "/old-images/old10.png", "/old-images/old11.png", "/old-images/old12.png", "/old-images/old13.png", "/old-images/old14.png", "/old-images/old15.png", "/old-images/old16.png", "/old-images/old17.png", "/old-images/old18.png", "/old-images/old19.png", "/old-images/old20.png" ] },
                { title: "SPIDER-MAN 2", director: "Sam Raimi", type: "Color", year: 2004, frames:["spider-images/spider1.png", "spider-images/spider2.png", "spider-images/spider3.png", "spider-images/spider4.png", "spider-images/spider5.png", "spider-images/spider6.png", "spider-images/spider7.png", "spider-images/spider8.png", "spider-images/spider9.png", "spider-images/spider10.png", "spider-images/spider11.png", "spider-images/spider12.png", "spider-images/spider13.png", "spider-images/spider14.png", "spider-images/spider15.png", "spider-images/spider16.png", "spider-images/spider17.png", "spider-images/spider18.png", "spider-images/spider19.png", "spider-images/spider20.png", "spider-images/spider21.png", "spider-images/spider22.png", "spider-images/spider23.png", "spider-images/spider24.png"]},
                { title: "THERE WILL BE BLOOD", director: "Paul Thomas Adnerson", type: "Color", year: 2007, frames: ["blood-images/blood1.png", "blood-images/blood2.png", "blood-images/blood3.png", "blood-images/blood4.png", "blood-images/blood5.png", "blood-images/blood6.png", "blood-images/blood7.png", "blood-images/blood8.png", "blood-images/blood9.png", "blood-images/blood10.png", "blood-images/blood11.png", "blood-images/blood12.png", "blood-images/blood13.png", "blood-images/blood14.png", "blood-images/blood15.png", "blood-images/blood16.png", "blood-images/blood17.png", "blood-images/blood18.png", "blood-images/blood19.png", "blood-images/blood20.png", "blood-images/blood21.png", "blood-images/blood22.png"] },
                { title: "INGLOURIOUS BASTERDS", director: "Quentin Tarantino", type: "Color", year: 2009, frames: ["basterds-images/basterds1.png", "basterds-images/basterds2.png", "basterds-images/basterds3.png", "basterds-images/basterds4.png", "basterds-images/basterds5.png", "basterds-images/basterds6.png", "basterds-images/basterds7.png", "basterds-images/basterds8.png", "basterds-images/basterds9.png", "basterds-images/basterds10.png", "basterds-images/basterds11.png", "basterds-images/basterds12.png", "basterds-images/basterds13.png", "basterds-images/basterds14.png", "basterds-images/basterds15.png", "basterds-images/basterds16.png", "basterds-images/basterds17.png", "basterds-images/basterds18.png", "basterds-images/basterds19.png", "basterds-images/basterds20.png", ]},
                { title: "SNOWPIERCER", director: "Bong Joon-Ho", type: "Color", year: 2013, frames:["snow-images/snow2.png", "snow-images/snow4.png", "snow-images/snow5.png", "snow-images/snow6.png", "snow-images/snow7.png", "snow-images/snow8.png", "snow-images/snow9.png", "snow-images/snow10.png", "snow-images/snow11.png", "snow-images/snow12.png", "snow-images/snow13.png", "snow-images/snow14.png", "snow-images/snow15.png", "snow-images/snow16.png", "snow-images/snow17.png", "snow-images/snow18.png", "snow-images/snow19.png", "snow-images/snow20.png", "snow-images/snow21.png"] },
                { title: "UNCUT GEMS", director: "Josh & Benny Safdie", type: "Color", year: 2019, frames: ["uncut-images/uncut1.png", "uncut-images/uncut2.png", "uncut-images/uncut3.png", "uncut-images/uncut4.png", "uncut-images/uncut5.png", "uncut-images/uncut6.png", "uncut-images/uncut7.png", "uncut-images/uncut8.png", "uncut-images/uncut9.png", "uncut-images/uncut10.png", "uncut-images/uncut11.png", "uncut-images/uncut12.png", "uncut-images/uncut13.png", "uncut-images/uncut14.png", "uncut-images/uncut15.png", "uncut-images/uncut16.png", "uncut-images/uncut17.png", "uncut-images/uncut18.png", "uncut-images/uncut19.png", "uncut-images/uncut20.png" ] },
                { title: "LAST NIGHT IN SOHO", director: "Edgar Wright", type: "Color", year: 2021, frames: ["soho-images/soho1.png", "soho-images/soho2.png", "soho-images/soho3.png", "soho-images/soho4.png", "soho-images/soho5.png", "soho-images/soho6.png", "soho-images/soho7.png", "soho-images/soho8.png", "soho-images/soho9.png", "soho-images/soho10.png", "soho-images/soho11.png", "soho-images/soho12.png", "soho-images/soho13.png", "soho-images/soho14.png", "soho-images/soho15.png", "soho-images/soho16.png", "soho-images/soho17.png", "soho-images/soho18.png", "soho-images/soho19.png", "soho-images/soho20.png" ] },
                { title: "BABYLON", director: "Damien Chazelle", type: "Color", year: 2022, frames:["babylon-images/babylon1.png", "babylon-images/babylon2.png", "babylon-images/babylon3.png", "babylon-images/babylon4.png", "babylon-images/babylon5.png", "babylon-images/babylon6.png", "babylon-images/babylon7.png", "babylon-images/babylon8.png", "babylon-images/babylon9.png", "babylon-images/babylon10.png", "babylon-images/babylon11.png", "babylon-images/babylon12.png", "babylon-images/babylon13.png", "babylon-images/babylon14.png", "babylon-images/babylon15.png", "babylon-images/babylon16.png", "babylon-images/babylon17.png", "babylon-images/babylon18.png", "babylon-images/babylon19.png", "babylon-images/babylon20.png" ] },
                { title: "MARTY SUPREME", director: "Josh Safdie", type: "Color", year: 2025, frames: ["marty-images/marty1.png", "marty-images/marty2.png", "marty-images/marty3.png", "marty-images/marty5.png", "marty-images/marty7.png", "marty-images/marty8.png", "marty-images/marty9.png", "marty-images/marty10.png", "marty-images/marty11.png", "marty-images/marty12.png", "marty-images/marty13.png", "marty-images/marty14.png", "marty-images/marty15.png", "marty-images/marty16.png", "marty-images/marty17.png", "marty-images/marty18.png", "marty-images/marty19.png", "marty-images/marty20.png" ] }
            ]
        },
        "70mm": {
            summary: "70mm film, often referred to as 65mm for the camera negative, is a large film format that offers superior image quality and resolution compared to smaller formats. It offers higher resolution and image quality compared to 35mm. It is often used for epic films and special presentations, providing a more immersive cinematic experience. By doubling the surface area of standard 35mm film, it drastically reduces grain and enhances chromatic precision, creating a scene with stability and profound clarity.",
            movies: [
                { title: "BEN-HUR", director: "William Wyler", type: "Color", year: 1959, frames: ["benhur-images/benhur1.png", "benhur-images/benhur2.png", "benhur-images/benhur3.png", "benhur-images/benhur4.png", "benhur-images/benhur5.png", "benhur-images/benhur6.png", "benhur-images/benhur7.png", "benhur-images/benhur8.png", "benhur-images/benhur9.png", "benhur-images/benhur10.png", "benhur-images/benhur11.png", "benhur-images/benhur12.png", "benhur-images/benhur13.png", "benhur-images/benhur14.png", "benhur-images/benhur15.png", "benhur-images/benhur16.png", "benhur-images/benhur17.png", "benhur-images/benhur18.png"] },
                { title: "WEST SIDE STORY", director: "Jerome Robbins & Robert Wise", type: "Color", year: 1961, frames: ["west-images/west1.png", "west-images/west2.png", "west-images/west3.png", "west-images/west4.png", "west-images/west5.png", "west-images/west6.png", "west-images/west7.png", "west-images/west8.png", "west-images/west9.png", "west-images/west10.png", "west-images/west11.png", "west-images/west12.png", "west-images/west13.png", "west-images/west14.png", "west-images/west15.png", "west-images/west16.png", "west-images/west17.png", "west-images/west18.png"] },
                { title: "LAWRENCE OF ARABIA", director: "David Lean", type: "Color", year: 1962, frames: ["lawrence-images/lawrence1.png", "lawrence-images/lawrence2.png", "lawrence-images/lawrence3.png", "lawrence-images/lawrence4.png", "lawrence-images/lawrence5.png", "lawrence-images/lawrence6.png", "lawrence-images/lawrence7.png", "lawrence-images/lawrence8.png", "lawrence-images/lawrence9.png", "lawrence-images/lawrence10.png", "lawrence-images/lawrence11.png", "lawrence-images/lawrence12.png", "lawrence-images/lawrence13.png", "lawrence-images/lawrence14.png", "lawrence-images/lawrence15.png", "lawrence-images/lawrence16.png", "lawrence-images/lawrence17.png", "lawrence-images/lawrence18.png", "lawrence-images/lawrence19.png", "lawrence-images/lawrence20.png"] },
                { title: "GRAND PRIX", director: "John Frankenheimer", type: "Color", year: 1966, frames: ["grand-images/grand1.png", "grand-images/grand2.png", "grand-images/grand3.png", "grand-images/grand4.png", "grand-images/grand5.png", "grand-images/grand6.png", "grand-images/grand7.png", "grand-images/grand8.png", "grand-images/grand9.png", "grand-images/grand10.png", "grand-images/grand11.png", "grand-images/grand12.png", "grand-images/grand13.png", "grand-images/grand14.png"] },
                { title: "2001: A SPACE ODYSSEY", director: "Stanley Kubrick", type: "Color", year: 1968, frames: ["2001-images/2001-1.png", "2001-images/2001-2.png", "2001-images/2001-3.png", "2001-images/2001-4.png", "2001-images/2001-5.png", "2001-images/2001-6.png", "2001-images/2001-7.png", "2001-images/2001-8.png", "2001-images/2001-9.png", "2001-images/2001-10.png", "2001-images/2001-11.png", "2001-images/2001-12.png", "2001-images/2001-13.png", "2001-images/2001-14.png", "2001-images/2001-15.png", "2001-images/2001-16.png", "2001-images/2001-17.png", "2001-images/2001-18.png", "2001-images/2001-19.png", "2001-images/2001-20.png"] },
                { title: "PATTON", director: "Franklin J. Schaffner", type: "Color", year: 1970, frames: ["patton-images/patton1.png", "patton-images/patton2.png", "patton-images/patton3.png", "patton-images/patton4.png", "patton-images/patton5.png", "patton-images/patton6.png", "patton-images/patton7.png", "patton-images/patton8.png", "patton-images/patton9.png", "patton-images/patton10.png", "patton-images/patton11.png", "patton-images/patton12.png", "patton-images/patton13.png", "patton-images/patton14.png", "patton-images/patton15.png", "patton-images/patton16.png", "patton-images/patton17.png", "patton-images/patton18.png", "patton-images/patton19.png", "patton-images/patton20.png"] },
                { title: "TRON", director: "Steven Lisberger", type: "Color", year: 1982, frames: ["tron-images/tron1.png", "tron-images/tron2.png", "tron-images/tron3.png", "tron-images/tron4.png", "tron-images/tron5.png", "tron-images/tron6.png", "tron-images/tron7.png", "tron-images/tron8.png", "tron-images/tron9.png", "tron-images/tron10.png", "tron-images/tron11.png", "tron-images/tron12.png", "tron-images/tron13.png", "tron-images/tron14.png", "tron-images/tron15.png", "tron-images/tron16.png", "tron-images/tron17.png", "tron-images/tron18.png", "tron-images/tron19.png", "tron-images/tron20.png", "tron-images/tron21.png", "tron-images/tron22.png"] },
                { title: "HAMLET", director: "Kenneth Branagh", type: "Color", year: 1996, frames: ["hamlet-images/hamlet1.png", "hamlet-images/hamlet2.png", "hamlet-images/hamlet3.png", "hamlet-images/hamlet4.png", "hamlet-images/hamlet5.png", "hamlet-images/hamlet6.png", "hamlet-images/hamlet7.png", "hamlet-images/hamlet8.png", "hamlet-images/hamlet9.png", "hamlet-images/hamlet10.png", "hamlet-images/hamlet11.png", "hamlet-images/hamlet12.png", "hamlet-images/hamlet13.png", "hamlet-images/hamlet14.png", "hamlet-images/hamlet15.png", "hamlet-images/hamlet16.png", "hamlet-images/hamlet17.png", "hamlet-images/hamlet18.png", "hamlet-images/hamlet19.png", "hamlet-images/hamlet20.png", "hamlet-images/hamlet21.png", "hamlet-images/hamlet22.png"] },
                { title: "THE MASTER", director: "Paul Thomas Anderson", type: "Color", year: 2012, frames: ["master-images/master1.png", "master-images/master2.png", "master-images/master3.png", "master-images/master4.png", "master-images/master5.png", "master-images/master6.png", "master-images/master7.png", "master-images/master8.png", "master-images/master9.png", "master-images/master10.png", "master-images/master11.png", "master-images/master12.png", "master-images/master13.png", "master-images/master14.png", "master-images/master15.png", "master-images/master16.png", "master-images/master17.png", "master-images/master18.png", "master-images/master19.png", "master-images/master20.png"] },
                { title: "THE HATEFUL EIGHT", director: "Quentin Tarantino", type: "Color", year: 2015, frames: ["hateful-images/hateful1.png", "hateful-images/hateful2.png", "hateful-images/hateful3.png", "hateful-images/hateful4.png", "hateful-images/hateful5.png", "hateful-images/hateful6.png", "hateful-images/hateful7.png", "hateful-images/hateful8.png", "hateful-images/hateful9.png", "hateful-images/hateful10.png", "hateful-images/hateful11.png", "hateful-images/hateful12.png", "hateful-images/hateful13.png", "hateful-images/hateful14.png", "hateful-images/hateful15.png", "hateful-images/hateful16.png", "hateful-images/hateful17.png", "hateful-images/hateful18.png", "hateful-images/hateful19.png", "hateful-images/hateful20.png"] },
                { title: "SINNERS", director: "Ryan Coogler", type: "Color", year: 2025, frames: ["sinners-images/sinners1.png", "sinners-images/sinners2.png", "sinners-images/sinners3.png", "sinners-images/sinners4.png", "sinners-images/sinners5.png", "sinners-images/sinners6.png", "sinners-images/sinners7.png", "sinners-images/sinners8.png", "sinners-images/sinners9.png", "sinners-images/sinners10.png", "sinners-images/sinners11.png", "sinners-images/sinners12.png", "sinners-images/sinners13.png", "sinners-images/sinners14.png", "sinners-images/sinners15.png", "sinners-images/sinners16.png", "sinners-images/sinners17.png", "sinners-images/sinners18.png", "sinners-images/sinners19.png", "sinners-images/sinners20.png"] }
            ]
        },
        "VistaVision": {
            summary: "Developed by Paramount in 1954, VistaVision revolutionaized the industry by rotating the 35mm film strip horizontally. By utlizing eight perforations per frame instead of the standard four, it created a negative with a significantly larger surface area, resulting in grain-free, high-definition image that was years ahead of its time. Originally designed to combat the rise of cheap TV films, VistaVision became the gold standard for visual effects and deep-focus cinematography. Even though it was abandoned by Hollywood after the huge failure of One-Eyed Jacks in 1961, this format came back in 2024, and is being widely used again.",
            movies: [
                { title: "WHITE CHRISTMAS", director: "Michael Curtiz", type: "Color", year: 1954, frames: ["christmas-images/christmas1.png", "christmas-images/christmas2.png", "christmas-images/christmas3.png", "christmas-images/christmas4.png", "christmas-images/christmas5.png", "christmas-images/christmas6.png", "christmas-images/christmas7.png", "christmas-images/christmas8.png", "christmas-images/christmas9.png", "christmas-images/christmas10.png", "christmas-images/christmas11.png", "christmas-images/christmas12.png", "christmas-images/christmas13.png", "christmas-images/christmas14.png", "christmas-images/christmas15.png", "christmas-images/christmas16.png", "christmas-images/christmas17.png", "christmas-images/christmas18.png"] },
                { title: "THE SEARCHERS", director: "John Ford", type: "Color", year: 1956, frames: ["searchers-images/searchers1.png", "searchers-images/searchers2.png", "searchers-images/searchers3.png", "searchers-images/searchers4.png", "searchers-images/searchers5.png", "searchers-images/searchers6.png", "searchers-images/searchers7.png", "searchers-images/searchers8.png", "searchers-images/searchers9.png", "searchers-images/searchers10.png", "searchers-images/searchers11.png", "searchers-images/searchers12.png", "searchers-images/searchers13.png", "searchers-images/searchers14.png", "searchers-images/searchers15.png", "searchers-images/searchers16.png", "searchers-images/searchers17.png", "searchers-images/searchers18.png", "searchers-images/searchers19.png", "searchers-images/searchers20.png", "searchers-images/searchers21.png", "searchers-images/searchers22.png"] },
                { title: "FUNNY FACE", director: "Stanley Donen", type: "Color", year: 1957, frames: ["funny-images/funny1.png", "funny-images/funny2.png", "funny-images/funny3.png", "funny-images/funny4.png", "funny-images/funny5.png", "funny-images/funny6.png", "funny-images/funny7.png", "funny-images/funny8.png", "funny-images/funny9.png", "funny-images/funny10.png", "funny-images/funny11.png", "funny-images/funny12.png", "funny-images/funny13.png", "funny-images/funny14.png", "funny-images/funny15.png", "funny-images/funny16.png", "funny-images/funny17.png", "funny-images/funny18.png", "funny-images/funny19.png", "funny-images/funny20.png"] },
                { title: "VERTIGO", director: "Alfred Hitchcock", type: "Color", year: 1958, frames: ["vertigo-images/vertigo1.png", "vertigo-images/vertigo2.png", "vertigo-images/vertigo3.png", "vertigo-images/vertigo4.png", "vertigo-images/vertigo5.png", "vertigo-images/vertigo6.png", "vertigo-images/vertigo7.png", "vertigo-images/vertigo8.png", "vertigo-images/vertigo9.png", "vertigo-images/vertigo10.png", "vertigo-images/vertigo11.png", "vertigo-images/vertigo12.png", "vertigo-images/vertigo13.png", "vertigo-images/vertigo14.png", "vertigo-images/vertigo15.png", "vertigo-images/vertigo16.png", "vertigo-images/vertigo17.png", "vertigo-images/vertigo18.png", "vertigo-images/vertigo19.png", "vertigo-images/vertigo20.png"] },
                { title: "NORTH BY NORTHWEST", director: "Alfred Hitchcock", type: "Color", year: 1959, frames: ["north-images/north1.png", "north-images/north2.png", "north-images/north3.png", "north-images/north4.png", "north-images/north5.png", "north-images/north6.png", "north-images/north7.png", "north-images/north8.png", "north-images/north9.png", "north-images/north10.png", "north-images/north11.png", "north-images/north12.png", "north-images/north13.png", "north-images/north14.png", "north-images/north15.png", "north-images/north16.png", "north-images/north17.png", "north-images/north18.png", "north-images/north19.png", "north-images/north20.png", "north-images/north21.png", "north-images/north22.png"] },
                { title: "ONE-EYED JACKS", director: "Marlon Brando", type: "Color", year: 1961, frames: ["jacks-images/jacks1.png", "jacks-images/jacks2.png", "jacks-images/jacks3.png", "jacks-images/jacks4.png", "jacks-images/jacks5.png", "jacks-images/jacks6.png", "jacks-images/jacks7.png", "jacks-images/jacks8.png", "jacks-images/jacks9.png", "jacks-images/jacks10.png", "jacks-images/jacks11.png", "jacks-images/jacks12.png", "jacks-images/jacks13.png", "jacks-images/jacks14.png", "jacks-images/jacks15.png", "jacks-images/jacks16.png", "jacks-images/jacks17.png", "jacks-images/jacks18.png"] },
                { title: "THE BRUTALIST", director: "Brady Corbet", type: "Color", year: 2024, frames: ["brutalist-images/brutalist1.png", "brutalist-images/brutalist2.png", "brutalist-images/brutalist3.png", "brutalist-images/brutalist4.png", "brutalist-images/brutalist5.png", "brutalist-images/brutalist6.png", "brutalist-images/brutalist7.png", "brutalist-images/brutalist8.png", "brutalist-images/brutalist9.png", "brutalist-images/brutalist10.png", "brutalist-images/brutalist11.png", "brutalist-images/brutalist12.png", "brutalist-images/brutalist13.png", "brutalist-images/brutalist14.png", "brutalist-images/brutalist15.png", "brutalist-images/brutalist16.png", "brutalist-images/brutalist17.png", "brutalist-images/brutalist18.png"] },
                { title: "ONE BATTLE AFTER ANOTHER", director: "Paul Thomas Anderson", type: "Color", year: 2025, frames: ["one-battle-images/one-battle1.png", "one-battle-images/one-battle2.png", "one-battle-images/one-battle3.png", "one-battle-images/one-battle4.png", "one-battle-images/one-battle5.png", "one-battle-images/one-battle6.png", "one-battle-images/one-battle7.png", "one-battle-images/one-battle8.png", "one-battle-images/one-battle9.png", "one-battle-images/one-battle10.png", "one-battle-images/one-battle11.png", "one-battle-images/one-battle12.png", "one-battle-images/one-battle13.png", "one-battle-images/one-battle14.png", "one-battle-images/one-battle15.png", "one-battle-images/one-battle16.png", "one-battle-images/one-battle17.png", "one-battle-images/one-battle18.png", "one-battle-images/one-battle19.png", "one-battle-images/one-battle20.png", "one-battle-images/one-battle21.png", "one-battle-images/one-battle22.png", "one-battle-images/one-battle23.png", "one-battle-images/one-battle24.png"] },
                { title: "BUGONIA", director: "Yorgos Lanthimos", type: "Color", year: 2025, frames: ["bugonia-images/bugonia1.png", "bugonia-images/bugonia2.png", "bugonia-images/bugonia3.png", "bugonia-images/bugonia4.png", "bugonia-images/bugonia5.png", "bugonia-images/bugonia6.png", "bugonia-images/bugonia7.png", "bugonia-images/bugonia8.png", "bugonia-images/bugonia9.png", "bugonia-images/bugonia10.png", "bugonia-images/bugonia11.png", "bugonia-images/bugonia12.png", "bugonia-images/bugonia13.png", "bugonia-images/bugonia14.png", "bugonia-images/bugonia15.png", "bugonia-images/bugonia16.png", "bugonia-images/bugonia17.png", "bugonia-images/bugonia18.png"] },
            ]
         },
         "IMAX": {
            summary: "Developed in the late 1960s as a specialized format for the grand-scale exhbition of science or nature documentary films, 15-perforation IMAX film is arguably the most powerful analog imaging system ever designed. Its frame is roughly ten times larger than standard 35mm, offering a resolution that challenges the limits of human eye. The vertical immerion of the format create a visceral, physical recation in the viewer, turning the act of watching a film into an act of presence within a hyper-real enviornment.",
            movies: [
                { title: "TIGER CHILD", director: "Donald Brittain", type: "Color", year: 1970, frames: ["tiger-images/tiger1.png"] },
                { title: "THE DREAM IS ALIVE", director: "Graeme Ferguson", type: "Color", year: 1985, frames: ["dream-images/dream1.png", "dream-images/dream2.png", "dream-images/dream3.png", "dream-images/dream4.png", "dream-images/dream5.png", "dream-images/dream6.png", "dream-images/dream7.png", "dream-images/dream8.png", "dream-images/dream9.png", "dream-images/dream10.png", "dream-images/dream11.png", "dream-images/dream12.png"] },
                { title: "ROLLING STONES: LIVE AT THE MAX", director: "Michael G. Madsen", type: "Color", year: 1991, frames: ["rolling-images/rolling1.png", "rolling-images/rolling2.png", "rolling-images/rolling3.png", "rolling-images/rolling4.png", "rolling-images/rolling5.png", "rolling-images/rolling6.png", "rolling-images/rolling7.png", "rolling-images/rolling8.png"] },
                { title: "THE DARK KNIGHT", director: "Christopher Nolan", type: "Color", year: 2008, frames: ["dark-knight-images/dark1.png", "dark-knight-images/dark2.png", "dark-knight-images/dark3.png", "dark-knight-images/dark4.png", "dark-knight-images/dark5.png", "dark-knight-images/dark6.png", "dark-knight-images/dark7.png", "dark-knight-images/dark8.png", "dark-knight-images/dark9.png", "dark-knight-images/dark10.png", "dark-knight-images/dark11.png", "dark-knight-images/dark12.png", "dark-knight-images/dark13.png", "dark-knight-images/dark14.png", "dark-knight-images/dark15.png", "dark-knight-images/dark16.png", "dark-knight-images/dark17.png", "dark-knight-images/dark18.png", "dark-knight-images/dark19.png", "dark-knight-images/dark20.png", "dark-knight-images/dark21.png", "dark-knight-images/dark22.png"] },
                { title: "MISSION: IMPOSSIBLE – GHOST PROTOCOL", director: "Brad Bird", type: "Color", year: 2011, frames: ["mission-images/mission1.png", "mission-images/mission2.png", "mission-images/mission3.png", "mission-images/mission4.png", "mission-images/mission5.png", "mission-images/mission6.png", "mission-images/mission7.png", "mission-images/mission8.png", "mission-images/mission9.png", "mission-images/mission10.png", "mission-images/mission11.png", "mission-images/mission12.png", "mission-images/mission13.png", "mission-images/mission14.png", "mission-images/mission15.png", "mission-images/mission16.png", "mission-images/mission17.png", "mission-images/mission18.png", "mission-images/mission19.png", "mission-images/mission20.png", "mission-images/mission21.png", "mission-images/mission22.png"] },
                { title: "INTERSTELLAR", director: "Christopher Nolan", type: "Color", year: 2014, frames: ["inter-images/inter1.png", "inter-images/inter2.png", "inter-images/inter3.png", "inter-images/inter4.png", "inter-images/inter5.png", "inter-images/inter6.png", "inter-images/inter7.png", "inter-images/inter8.png", "inter-images/inter9.png", "inter-images/inter10.png", "inter-images/inter11.png", "inter-images/inter12.png", "inter-images/inter13.png", "inter-images/inter14.png", "inter-images/inter15.png", "inter-images/inter16.png", "inter-images/inter17.png", "inter-images/inter18.png", "inter-images/inter19.png", "inter-images/inter20.png", "inter-images/inter21.png", "inter-images/inter22.png", "inter-images/inter23.png", "inter-images/inter24.png"] },
                { title: "DUNKIRK", director: "Christopher Nolan", type: "Color", year: 2017, frames: ["dunkirk-images/dunkirk1.png", "dunkirk-images/dunkirk2.png", "dunkirk-images/dunkirk3.png", "dunkirk-images/dunkirk4.png", "dunkirk-images/dunkirk5.png", "dunkirk-images/dunkirk6.png", "dunkirk-images/dunkirk7.png", "dunkirk-images/dunkirk8.png", "dunkirk-images/dunkirk9.png", "dunkirk-images/dunkirk10.png", "dunkirk-images/dunkirk11.png", "dunkirk-images/dunkirk12.png", "dunkirk-images/dunkirk13.png", "dunkirk-images/dunkirk14.png", "dunkirk-images/dunkirk15.png", "dunkirk-images/dunkirk16.png", "dunkirk-images/dunkirk17.png", "dunkirk-images/dunkirk18.png", "dunkirk-images/dunkirk19.png", "dunkirk-images/dunkirk20.png", "dunkirk-images/dunkirk21.png", "dunkirk-images/dunkirk22.png"] },
                { title: "TENET", director: "Christopher Nolan", type: "Color", year: 2020, frames: ["tenet-images/tenet1.png", "tenet-images/tenet2.png", "tenet-images/tenet3.png", "tenet-images/tenet4.png", "tenet-images/tenet5.png", "tenet-images/tenet6.png", "tenet-images/tenet7.png", "tenet-images/tenet8.png", "tenet-images/tenet9.png", "tenet-images/tenet10.png", "tenet-images/tenet11.png", "tenet-images/tenet12.png", "tenet-images/tenet13.png", "tenet-images/tenet14.png", "tenet-images/tenet15.png", "tenet-images/tenet16.png", "tenet-images/tenet17.png", "tenet-images/tenet18.png", "tenet-images/tenet19.png", "tenet-images/tenet20.png"] },
                { title: "OPPENHEIMER", director: "Christopher Nolan", type: "Color / Black & white", year: 2023, frames: ["oppen-images/oppen1.png", "oppen-images/oppen2.png", "oppen-images/oppen3.png", "oppen-images/oppen4.png", "oppen-images/oppen5.png", "oppen-images/oppen6.png", "oppen-images/oppen7.png", "oppen-images/oppen8.png", "oppen-images/oppen9.png", "oppen-images/oppen10.png", "oppen-images/oppen11.png", "oppen-images/oppen12.png", "oppen-images/oppen13.png", "oppen-images/oppen14.png", "oppen-images/oppen15.png", "oppen-images/oppen16.png", "oppen-images/oppen17.png", "oppen-images/oppen18.png", "oppen-images/oppen19.png", "oppen-images/oppen20.png"] }
            ]
         }
    };
    
    
    $(".sidebar a").click(function(e) {
        e.preventDefault();
        let target = $(this).attr("id").replace("nav-", "section-");
        $(".page-section").hide();
        $("#"+target).show();
        if(target==="section-archive"){
            $("#archive-detail").hide();
            $("#archive-default").show();
        }
    });
 
    $(".format-box").click(function() {
        $(this).addClass("active").siblings().removeClass("active");
        let format = $(this).data("format"); 
        let data = archiveData[format];
        if(!data) return; 

        // $("#archive-default").hide();
        $("#archive-detail").css("display", "flex");
        // $(window).scrollTop(0);

        // $("#selected-format-box").attr("class", "ratio-box frame-" + format);
        $("#format-title").text(format);
        $("#format-summary").text(data.summary);
        
        $("#movie-list").empty();
        data.movies.forEach(function(movie, i) {
            $("#movie-list").append(`<li data-format="${format}" data-index="${i}">${movie.title}</li>`);
        });

        $("#movie-list li").first().trigger("click");

        if($(window).width() <= 768){
            $('html, body').animate({
                scrollTop: $("#archive-detail").offset().top - 80
            }, 300);
        }else{
            $("#archive-detail").scrollTop(0);
        }
    });

$(document).on("click", "#movie-list li", function() {
    const format = $(this).data("format");
    const index = $(this).data("index");
    const movie = archiveData[format].movies[index];

    $(this).addClass("active").siblings().removeClass("active");

    $("#movie-title").text(movie.title);
    $(".info-director").text(movie.director);
    $(".info-year").text(movie.year);
    $(".info-type").text(movie.type);

    $("#movie-frames").empty();

    movie.frames.forEach(function(src) {
    let path;

    if (src.includes('/')) {
        path = `images/${src}`; 
    } 
    else if (movie.folder) {
        path = `images/${movie.folder}/${src}`;
    } 
    else {
        path = `images/${src}`;
    }
    
    $("#movie-frames").append(`<img src="${path}" class="frame-${format}" alt="${movie.title} frame">`)
    });


});

const cursor = document.createElement("div");

cursor.style.width = "20px";
cursor.style.height = "20px";
cursor.style.background = "orange";
cursor.style.borderRadius = "50%";
cursor.style.position = "fixed";
cursor.style.pointerEvents = "none";
cursor.style.transform = "translate(-50%, -50%)";
cursor.style.display = "none";
cursor.style.zIndex = "9999";

document.body.appendChild(cursor);

document.addEventListener("mousemove", (e) => {
    cursor.style.left = e.clientX + "px";
    cursor.style.top = e.clientY + "px";
});

$(document).on("mouseenter", "#movie-list li", function() {
    const index = $(this).data("index");
    const format = $(this).data("format");
    const movie = archiveData[format].movies[index];

    if(movie.title === "MARTY SUPREME"){
        cursor.style.display = "block";          
        document.body.style.cursor = "none";     
    } else {
        cursor.style.display = "none";           
        document.body.style.cursor = "default";  
    }
});

$(document).on("mouseleave", "#movie-list li", function(){
    cursor.style.display = "none";
    document.body.style.cursor = "default";
    
});

});



// setTimeout(function(){
// $("#box-35mm").click();
// },1000)

